backend/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
	
	path("", views.HomeView.as_view(), name="home"),
	path("name_generator/", views.NameGenerator.as_view(), name="name_generator"),
    path("generate-logo/", views.GenerateLogoView.as_view(), name="generate-logo"),
]

backend/django_chatgpt/urls.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
]

if settings.DEBUG == 1:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/views/generate_logo.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.views import generic
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.conf import settings

# --------------------------------------------------------------
# App imports
# --------------------------------------------------------------
from core.forms import InputForm

# --------------------------------------------------------------
# Project imports
# --------------------------------------------------------------
from utils.decorators import ajax_required
from utils.mixins import FormErrors

# --------------------------------------------------------------
# 3rd Party imports
# --------------------------------------------------------------
import openai

openai.api_key = settings.OPENAI_API_KEY

class GenerateLogoView(generic.FormView):
    """
    FormView used for our generate logo page.

    **Template:**

    :template:`generate_logo.html`
    """
    template_name = "generate_logo.html"
    form_class = InputForm
    success_url = "/"

    @method_decorator(ajax_required)
    def post(self, request,*args, **kwargs):
        data = {'result': 'Error', 'message': "Something went wrong, please try again", "redirect": False, "data":None}
        form = InputForm(request.POST)
        if form.is_valid():

            input = form.cleaned_data.get("input")

            response = openai.Image.create(
                prompt=input,
                n=1,
                size="1024x1024"
            )
            data.update({
                'result': "Success",
                'message': "ChatGPT has created this logo",
                'data': response['data'][0]['url']
            })
            return JsonResponse(data)

        else:
            data["message"] = FormErrors(form)
            return JsonResponse(data, status=400)

backend/templates/generate_analysis.html
{% extends "index.html" %}
{% load static %}

<!--...-->
{% block content %}

  <script src="js/bootstrap.min.js"></script>
  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'main.js' %}"></script>




      <div class='contain_report'>
        <form action="{% url 'core:home' %}" method="post" id="basicform">
          {% csrf_token %}
          {{form.input}}
          <button type="submit" >Generate Report</button>
        </form>

        <div id="loading_info"></div>
        <div id="wordcloud"></div>
        <div id="chartContainer1" style="height: 370px; width: 40%;"></div>
        <div id="chatgpt1"></div>
        <div id="chartContainer2" style="height: 370px; width: 40%;"></div>
        <div id="chatgpt2"></div>


     </div>
{% endblock %}

backend/templates/generate_logo.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Django ChatGPT demo</title>
  <link
    rel="shortcut icon"
    href="{% static 'dog.png' %}"
  />
  <link rel="stylesheet" href="{% static 'main.css' %}" />
</head>

<body>
  {% comment %} <img src="{% static 'dog.png' %}" class="icon" /> {% endcomment %}
  <h3>Use AI to create a logo</h3>
  <form action="{% url 'core:generate-logo' %}" method="post" id="basicimageform">
    {% csrf_token %}
    {{form.input}}
    <button type="submit" >Generate logo</button>
  </form>

  <div class="result">

  </div>

  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'main.js' %}"></script>
</body>

backend/templates/generate_name.html
{% extends "index.html" %}
{% load static %}

{% block content %}
  <script src="js/bootstrap.min.js"></script>

  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'namegenerator.js' %}"></script>






      <div class='contain_report'>
        <form action="{% url 'core:name_generator' %}" method="post" id="basicform">
          {% csrf_token %}
          {{form.input}}
          <button type="submit" >Generate Names</button>
        </form>

        <div id="generate_name"></div>
 

{% endblock %}

backend/templates/index.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Django ChatGPT demo</title>
  <link
    rel="shortcut icon"
 
  />
  <link rel="stylesheet" href="{% static 'main.css' %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
</head>

<body>
   
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand">Chatgpt</a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Analyze My Business</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/name_generator">Generate My Product Names</a>
              </li>

            </ul>
          </div>
        </div>
      </nav>

    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

  <meta charset="utf-8">
  <script src="https://d3js.org/d3.v4.js"></script>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->

  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  <!-- Load d3-cloud -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-cloud/1.2.5/d3.layout.cloud.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-cloud/1.2.5/d3.layout.cloud.js"></script>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="https://rawgit.com/jasondavies/d3-cloud/master/build/d3.layout.cloud.js"></script>

  <!-- Load d3.js -->


  <script>
    //console.log({{data}})
    //$('.result').append({{data.data}});
  </script>
</body>